name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          # Auto-detect your username instead of hardcoding
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move to target folder
        run: |
          mkdir -p .github-snake
          cp dist/* .github-snake/ || true

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .github-snake/
          git diff --cached --quiet || git commit -m "🐍 update GitHub contribution snake"
          # Push to the current branch even if its name changes
          git push origin HEAD:${GITHUB_REF_NAME}
