name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ IMPORTANT: Allow write permission to push to main

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: nashutosh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move to target folder
        run: |
          mkdir -p .github-snake
          cp dist/* .github-snake/

      - name: Commit and push to main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .github-snake/
          git commit -m "🐍 update GitHub contribution snake" || echo "nothing to commit"
          git push origin main
